; elkay firmware: DEC LK401 to USB HID.

[platformio]
default_envs = micro

[env]
framework = arduino
monitor_speed = 115200

[env:micro]
platform = atmelavr
board = micro

[env:teensy2]
platform = teensy
board = teensy2
build_flags = -D USB_SERIAL
